nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.4.cjs
npmScopes:
  react-native-documents:
    npmRegistryServer: https://npm.pkg.github.com
    npmAuthToken: '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'
